include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  # KUBE_INGRESS_BASE_DOMAIN: domain.example.com

  POSTGRES_ENABLED: 'false'
  TEST_DISABLED: 'true'
  CODE_QUALITY_DISABLED: 'true'
  LICENSE_MANAGEMENT_DISABLED: 'true'
  PERFORMANCE_DISABLED: 'true'
  SAST_DISABLED: 'true'
  SECRET_DETECTION_DISABLED: 'true'
  DEPENDENCY_SCANNING_DISABLED: 'true'
  CONTAINER_SCANNING_DISABLED: 'true'
  DAST_DISABLED: 'true'
  
  K8S_SECRET_SOCKET_ONLY_ALLOW_ORIGINS: https://$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN,https://$CI_PROJECT_PATH_SLUG-staging.$KUBE_INGRESS_BASE_DOMAIN,https://$CI_PROJECT_ID-$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN


# Override Staging database URL
staging:
  variables:
    DATABASE_URL: $DATABASE_URL_STAGING
    
# Override Review database URL
review:
  variables:
    DATABASE_URL: $DATABASE_URL_STAGING
    
# Override Production database URL
production:
  variables:
    DATABASE_URL: $DATABASE_URL_PRODUCTION
    HELM_UPGRADE_EXTRA_ARGS: --set postgresql.enabled=false
    
timed rollout 100%:
  variables:
    DATABASE_URL: $DATABASE_URL_PRODUCTION
    HELM_UPGRADE_EXTRA_ARGS: --set postgresql.enabled=false
    
rollout 100%:
  variables:
    DATABASE_URL: $DATABASE_URL_PRODUCTION
    HELM_UPGRADE_EXTRA_ARGS: --set postgresql.enabled=false
